import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name : " Tano and  Rex " ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647949648/jedistore/Ahsoka_Tano_and_Captain_Rex_Action_Figure_Set_hy5ggg.jpg",
    rating : "4.3",
    orignalPrice : 3000,
    discount : 10,
    categoryName :"Toys",
    tag : "New Arrival",
    description : "War veteran Tano and  Rex will make powerful addition to your Toybox.It includes blaster and Lightsaber.",
},
{
    _id: uuid(),
    name : "Galactic Jacket" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647949649/jedistore/galactic-starcruiser-outfits-shopdisney-2_y2ai0m.jpg",
    rating : "4.1",
    orignalPrice : 2000,
    discount : 30,
    categoryName :"Clothes",
    tag : "Trending",
    description : "Imagine yourself with  Star Wars: Galactic Starcruiser adventure with this Captain's Jacket.",
},
{
    _id: uuid(),
    name : "Star Wars:Formal Tunic" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647949649/jedistore/Formal-Tunic-Star-Wars_mariyn.jpg",
    rating : "2.3",
    orignalPrice : 3500,
    discount : 10,
    categoryName :"Clothes",
    tag : "Trending",
    description : "This elegant and stylish Formal Tunic strikes the right tone as you experience your exciting Star Wars mission.",
},
{
    _id: uuid(),
    name : "Fighter Pewter Vehicle" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647974183/jedistore/TIE_Fighter_Pewter_Vehicle_by_Royal_Selangor_xa7uk4.jpg",
    rating : "3.3",
    orignalPrice : 500,
    discount : 5,
    categoryName :"Collectibles",
    tag : "",
    description : "TIE Fighter Pewter Vehicle by Royal Selangor will make powerful addition to your Collectibles.",
},
{
    _id: uuid(),
    name : "Jedi: Fallen Order Mug" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647974183/jedistore/jedi-merchandise_bnbbpe.jpg",
    rating : "4.4",
    orignalPrice : 1000,
    discount : 20,
    categoryName :"Merchandise",
    tag : "",
    description : "Gold Star Wars Jedi: Fallen Order Mug is perfect choice for your smoothing coffee.",
},
{
    _id: uuid(),
    name : "The Mandalorian Toy" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647974183/jedistore/The_mandalorian_Talking_action_Figure_gnqnfr.jpg",
    rating : "4.3",
    orignalPrice : 700,
    discount : 20,
    categoryName :"Toys",
    tag : "",
    description : "The title character from the Disney+ series comes to life as this The Mandalorian Talking Action Figure.",
},
{
  _id: uuid(),
    name : "Stormtrooper Bracelet" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647974183/jedistore/Stormtrooper_Leather_Bracelet_figmty.jpg",
    rating : "4.3",
    orignalPrice : 300,
    discount : 10,
    categoryName :"Merchandise",
    tag : "",
    description : "Keep Imperial forces within arm's with stormtrooper bracelet.Crafted in leather, personalize with your own signature.",
},
{
  _id: uuid(),
    name : "Bail Organ jacket" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647984026/jedistore/Bail-Organa-jacket_h9hn5i.jpg",
    rating : "4.3",
    orignalPrice : 5000,
    discount : 20,
    categoryName :"Clothes",
    tag : "",
    description : "Get into character as you prepare for your epic Star Wars: Galactic Starcruiser adventure.",
},
{
  _id: uuid(),
    name : "Darth Vader Toy Figure" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647984108/jedistore/Darth_Vader_Talking_Action_Figure_htftov.jpg",
    rating : "4.3",
    orignalPrice : 4000,
    discount : 30,
    categoryName :"Toys",
    tag : "",
    description : "Lord Vader would like to have a word with you.Includes motion-activated Lightsaber with light and sound effects.",
},
{
  _id: uuid(),
    name : "Rey Pewter Figurine" ,
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647984179/jedistore/Rey_Pewter_Figurine_by_Royal_Selangor_qtubsc.jpg",
    rating : "4.3",
    orignalPrice : 200,
    discount : 10,
    categoryName :"Collectibles",
    tag : "",
    description : "Crafted in pewter by skilled artisans of Royal Selangor,limited edition captures every detail of courageous warrior.",
},
{
  _id: uuid(),
    name : "YODA Pewter Figurine ",
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647984180/jedistore/YODA_Pewter_Figurine_by_Royal_Selangor_fmng9f.jpg",
    rating : "4.3",
    orignalPrice : 2000,
    discount : 10,
    categoryName :"Collectibles",
    tag : "",
    description : " 'When nine hundred years old you reach, look as good you will not.' Legendary Yoda ",
},
{
  _id: uuid(),
    name : "DarthVader water bottle",
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647984180/jedistore/star-wars-darth-vader-water-bottle-merchandise_phlhxm.jpg",
    rating : "4.3",
    orignalPrice : 400,
    discount : 20,
    categoryName :"Merchandise",
    tag : "",
    description : "Drink more water. Your skin, hair, body, and mind will thank you. Dang, hydration never looked so good!",
},
{
  _id: uuid(),
    name : "Boba Fett Jetpack Toy",
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647984180/jedistore/normal_disney-boba-fett-jetpack-for-kids-the-book-of-boba-fett-variant_gybml8.jpg",
    rating : "4.3",
    orignalPrice : 1000,
    discount : 10,
    categoryName :"Toys",
    tag : "",
    description : "They'll recreate the adventure of Star Wars Book Boba Fett with the mysterious bounty hunter's jetpack.",
},
{
  _id: uuid(),
    name : "Falcon Pewter",
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647984180/jedistore/Millennium_Falcon_Pewter_Replica_by_Royal_Selangor_Star_Wars_pqt5s4.jpg",
    rating : "4.3",
    orignalPrice : 3500,
    discount : 40,
    categoryName :"Collectibles",
    tag : "",
    description : " ''It's the ship that made the Kessel Run in less than twelve parsecs.'' Replica by Royal Selangor – Star Wars ",
},
{
  _id: uuid(),
    name : "R2-D2 Pewter Figurine",
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1647984181/jedistore/R2-D2_Pewter_Figurine_Canister_by_Royal_Selangor_qfxdt9.jpg",
    rating : "4.3",
    orignalPrice : 3700,
    discount : 10,
    categoryName :"Collectibles",
    tag : "",
    description : "The R2-D2 astromech droid is noted for its deadpan humour and enduring friendship with protocol C-3PO.",
},
{
  _id: uuid(),
    name : "Short Sleeve T-Shirt",
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1648018604/jedistore/download_uhulpp.jpg",
    rating : "3.2",
    orignalPrice : 500,
    discount : 10,
    categoryName :"Clothes",
    tag : "",
    description : "Celebrate all things Star Wars in this celestial design reimagining the iconic series logo.",
},
{
  _id: uuid(),
    name : " Long Sleeve T-Shirt ",
    imageUrl : "https://res.cloudinary.com/sushil-mod/image/upload/v1648019290/jedistore/download_1_gzwhd5.jpg",
    rating : "2.3",
    orignalPrice : 900,
    discount : 10,
    categoryName :"Clothes",
    tag : "",
    description : "With hearts in eyes,Darth Vader with invitation to team up and the promise ''Together we can rule the galaxy.''",
},
];
